const arrLang = {
    ja: {
        languageJa:"日本語",
        languageEn:"英語",
        // header
        school: "学校案内",
        course: "コース案内",
        placement:"就職サポート",
        instructor:"講師紹介",
        faq:"よくある質問",
        sushiOwners:"寿司店様へ",
        //footer
        address:"〒104-0061<br>東京都中央区銀座２丁目１１−１９国光ビル4階",
        tel:"TEL：03-6278-7586<br>営業日：月・火・木・金・土(祝日除く)",
        access:"＜アクセス＞<br>銀座一丁目駅から徒歩　2分<br>東銀座駅から徒歩　4分<br>銀座駅から徒歩　6分<br>有楽町駅から徒歩　8分",
        intensive:"集中特訓コース",
        company:"会社概要",
        tems:"利用規約",
        //FV
        mvisualTopH1:"東京寿司職人育成アカデミー",
        mvisualTopH2:"世界で活躍できる寿司職人へ",
        mvisualSub:"〈2025年6月~8月コース限定〉<br>総額77万円が今だけ<span>30</span>万円に！残り5枠！",
        //CTA
        btn_cta01:"資料請求、無料見学会は<br>こちらをクリック",
        btn_cta02:"お問い合わせはこちら",
        btn_cta03:"入学願書申し込み",
        cta_text:"電話でのお問い合わせもお待ちしております。",
        //東京寿司職人<br>育成アカデミーとは
        academy_jp:"東京寿司職人<br>育成アカデミーとは",
        academy_sec:"本物の職人のもと最短2ヶ月で<br>寿司職人を目指す",
        academy_text:"我々は2ヶ月という短期間で０から国内外のどこでも即戦力で通用する高いレベルの寿司職人を育成するアカデミーです。<br>米を炊く、魚を捌く、寿司を握るといった基本の仕事も就業先によって全て変わってくることがほとんどです。<br>当アカデミーでは高級店、大衆店、回転寿司の仕事、また海外で調理器具がない、水や魚、調味料が違うといった場合の仕事も学んで頂きます。<br>当アカデミー卒業後は高級店、大衆店、回転寿司また海外での就職もサポートさせて頂きます。",
        //course
        course_btn:"コースをもっと見る",
        cta_sec_btn01:"まずは資料請求（無料）",
        //instructors
        instructors_jp:"業界トップクラスの<br>現役寿司職人が講師陣",
        instructors_text:"包丁の使い方から握り方まで、基礎から丁寧に教えます。<br>少人数制で、きめ細やかな指導を行うため、初心者の方でも安心して受講できます。",
        instructors_btn:"講師陣をもっと見る",
        //enroll
        enroll_jp:"入学希望の方へ",
        tuition:"学費",
        maintenance:"受験生の1日",
        enroll_maintenance:"動画で見る<br>レッスン",
        //strengths
        strengths_jp:"東京寿司職人アカデミーの強み",
        strengths_list1:"高級鮨店<br><span>「銀座 鮨 佑」</span>と<br>提携",
        strengths_list2:"医療・IT・人材など幅広い事業展開を行う<br class='sp_break'>DYMグループだから<br><span>卒業後の紹介先多数</span>",
        strengths_list3:"<span>五つ星ホテル</span>や<br><span>ミシュラン獲得店</span>も<br>紹介可能",
        //faq
        faq_1:"卒業後のサポートはありますか？",
        faq_2:"当校の運営母体では国内外で広く人材事業、WEB事業、不動産事業等の運営もしております。国内外問わずご希望にそった就職、開業のサポートをさせていただきます。",
        faq_3:"入学資格はありますか？",
        faq_4:"ございません。しっかり学んで卒業後はしっかり稼いでください。",
        faq_5:"調理経験が無くても大丈夫ですか？",
        faq_6:"当校では基礎から学んで頂きます。<br>包丁の握り方、道具の手入れから学んで頂きます。<br>また経験者の方々も普通は既製品に頼るようなものも手作り出来る様なカリキュラムを組んでおりますので新たな技術の習得が可能です。",
        faq_7:"２ヶ月で寿司職人になれますか？",
        faq_8:"技術はもちろん寿司職人としての心構えからカウンターでの所作、英語での料理説明等、現場で通用するレベルまで習得して頂きます。",
        faq_btn:"もっと見る",
        //access page
        home:"ホーム",
        reasons_jp:"東京寿司職人育成アカデミーが<br class='sp_break'>選ばれるポイント",
        point1_title:"短期集中カリキュラム",
        point1_txt:"当校は2ヶ月の短期集中授業になります。<br>毎回、握りと包丁の授業がありますので卒業時には体が覚えてるレベルに成長出来ます。",
        point2_title:"多種多様な現場で即戦力に！",
        point2_txt:"魚1本にしてもクオリティー重視、スピード重視、熟成させる、冷凍する等の色々な捌き方を覚えて頂きます。<br>普通のお店では既製品を使うガリやオボロ等の授業もあります。",
        point3_title:"就職・開業サポート",
        point3_txt:"当校の運営母体である株式会社DYM（リンクも貼る）は、国内外で人材事業、WEB事業、不動産事業等の幅広い運営をしておりますので卒業後の就職・開業支援など、手厚いサポートを行います。",
        comparison_jp:"他校比較",
        comparison_text:"本物の職人のもと、世界で活躍できる寿司職人を目指せます。",
        comparison_th1:"寿司職人育成アカデミー",
        comparison_th2:"調理師学校",
        comparison_th3:"コマ制寿司教室",
        comparison_th4:"寿司職人養成スクール",
        comparison_td1:"就学期間",
        comparison_td2:"2ヶ月",
        comparison_td3:"24か月",
        comparison_td4:"1日～6か月",
        comparison_td5:"2か月",
        comparison_td6:"授業時間",
        comparison_td7:"概ね200時間",
        comparison_td8:"概ね３５００時間<br>（座学中心）",
        comparison_td9:"1～200時間",
        comparison_td10:"概ね200時間",
        comparison_td11:"カリキュラム",
        comparison_td12:"実際の現場に合わせた技術、知識の習得",
        comparison_td13:"寿司より和食に関しての<br>授業中心",
        comparison_td14:"自分の学びたい授業のみ、（コマ数多く購入しないと受けれない授業あり）",
        comparison_td15:"短期間で握りに特化した授業",
        comparison_td16:"クラス定員",
        comparison_td17:"12名",
        comparison_td18:"約40名",
        comparison_td19:"12名",
        comparison_td20:"24名",
        comparison_td21:"学費",
        comparison_td22_p1:"<span class='lrg'>700,000円</span>（税抜）",
        comparison_td22_p2:"770,000円 <span class='sm'>税込（10％）</span>",
        comparison_td23:"入学金　250,000円<br>授業料　3540,000円",
        comparison_td24:"1コマ　7,000円～<br>200コマ　700,000円",
        comparison_td25:"入学金　165,000円<br>授業料　715,000円",
        comparison_td26:"食材",
        comparison_td27:"高級店と同じ捌かれていない状態の多種多様な食材の仕入れ",
        comparison_td28:"基本的な魚介類を大量仕入れ",
        comparison_td29:"授業の内容に合った魚介類",
        comparison_td30:"捌かれて柵の状態の食材も有り",
        comparison_td31:"卒業後の支援",
        comparison_td32:"国内外問わずご希望に沿った就職先のご紹介、就業後の様々なご相談、開業のご相談も受け賜ります。",
        comparison_td33:"求人票メイン",
        comparison_td34:"主に自社採用",
        comparison_td35:"専門の求人サイト",
        access_jp:"アクセス",
        access_address:"東京寿司職人アカデミー　銀座校",
        access_post:"〒104-0061<br>東京都中央区銀座2丁目11-19国光ビル4階",
        access_transportation:"交通アクセス",
        access_station:"「銀座一丁目」駅徒歩1分<br>「銀座」駅徒歩5分",
        map_view:"googleマップで見る",
        //course and fees page
        course_fees_title:"コース案内・学費",
        course_features:"コースの特長",
        course_tuition:"学費",
        course_tuition_loan:"学費ローン",
        course_information:"未経験の人でも技術と知識をしっかりと付けれるコースになっております。",
        course_centent:"コース内容",
        course_centent_txt:"週５回の短期集中コース",
        course_enrollment:"入学金",
        course_enrollment_txt:"22万円（税込）",
        course_fees:"授業料",
        course_fees_txt:"55万円（税込）",
        course_payment:"分割払い",
        course_payment_txt:"24回払いで月々33,712 円",
        course_day:"授業曜日",
        course_day_txt:"毎週　月・火・木・金・土",
        course_hours:"授業時間",
        course_hours_txt:"9:00~16:00",
        details:"詳細はこちら",
        course_features_title:"業界最安値水準・最高品質の授業をご提供",
        course_features_txt:"入塾費用の負担をできるだけ下げれるように、一般的には88～110万程度の学費から東京寿司職人育成アカデミーでは最低料金まで下げております。学費ローンの利用も可能なので、24回払いであれば金利込みで月々33,712円と入塾中のバイト代でも十分に支払いが可能でございます。銀座の一流寿司店での実践や、一流講師の授業、と他のアカデミーでは出来ない品質で行っております。",
        course_loans_txt1:"ローンに関してもご紹介の会社で楽々審査が可能です。",
        course_loans_txt2:"2ヵ月集中特訓コース",
        course_loans_fees:"全額77万円<span class='sm'>（税込）</span>",
        course_loans_th1:"分割",
        course_loans_th2:"金額/月(税込)",
        course_loans_td1:"24回",
        course_loans_td2:"37,712円",
        course_loans_td3:"36回",
        course_loans_td4:"23,008円",
        course_loans_td5:"60回",
        course_loans_td6:"14,460円",
        course_loans_btn_title:"資料請求　随時受付中！",
        //就職サポート page
        placement_support:"株式会社DYMが<br class='sp'>全面サポートいたします！",
        placement_support_title:"DYMグループは従業員数2000人超、売上300億超の大手企業です。<br>DYMグループは人材紹介事業ではオリコンで顧客満足度1位など高い評価をいただいておりますので、<br>卒業後の就職のサポートでは「東京寿司職人育成アカデミー」は最高水準をお約束いたします。",
        //instructor page
        instructor_jp:"経験豊富な講師陣",
        instructor_represent:"代表講師",
        instructor_represent_name:"木立 健太",
        instructor_represent_txt1:"国内外の名店、高級店、有名ホテルにて３０年以上の現場経験を経て講師に就任。",
        instructor_represent_txt2:"経歴 ※一部抜粋",
        instructor_th1:"日本国内",
        instructor_td1:"寿司屋の市勘<br>（代官山の有名人御用達高級店）",
        instructor_td2:"atelierMORIMOTO・XEX<br>（六本木の元料理の鉄人プロデュース　人気高級店）",
        instructor_td3:"たん熊北店　ロイヤルパークホテル汐留店　寿司責任者<br>（昭和３年創業の老舗京料理店）",
        instructor_td4:"グランドハイアット東京　六緑<br>（東京でも屈指のラグジュアリーホテル直営寿司店）",
        instructor_td5:"ANA　羽田、成田空港航空会社ラウンジ",
        instructor_td6:"鮨　塩釜港　銀座　極<br>（銀座の高級有名店）",
        instructor_th2:"米国",
        instructor_td7:"sushizen<br> （米国NY,マンハッタンの老舗高級店）",
        instructor_th3:"独国",
        instructor_td8:"ザ・ウェスティングランド・フランクフルト　鮨元<br>（ドイツの老舗高級店）",
        //faq page
        faq_dt1:"卒業後のサポートはありますか？",
        faq_dd1:"当校の運営母体では国内外で広く人材事業、WEB事業、不動産事業等の運営もしております。国内外問わずご希望にそった就職、開業のサポートをさせていただきます。",
        faq_dt2:"入学資格はありますか？",
        faq_dd2:"ございません。しっかり学んで卒業後はしっかり稼いでください。",
        faq_dt3:"調理経験が無くても大丈夫ですか？",
        faq_dd3:"当校では基礎から学んで頂きます。<br>包丁の握り方、道具の手入れから学んで頂きます。<br>また経験者の方々も普通は既製品に頼るようなものも手作り出来る様なカリキュラムを組んでおりますので新たな技術の習得が可能です。",
        faq_dt4:"２ヶ月で寿司職人になれますか？",
        faq_dd4:"技術はもちろん寿司職人としての心構えからカウンターでの所作、英語での料理説明等、現場で通用するレベルまで習得して頂きます。",
        faq_dt5:"地方在住ですが、寮などの施設はありますか？",
        faq_dd5:"寮などの施設はございませんが、当校運営母体が不動産事業等も運営していますのでご相談ください。",
        faq_dt6:"学費の分割払いは可能ですか？",
        faq_dd6:"ローンの取り扱いがございますのでお気軽にお問い合わせください。",
        faq_dt7:"年齢制限はありますか？",
        faq_dd7:"ありません。やる気と元気があれば大丈夫です。",
        faq_dt8:"海外在住なのですが面談や見学は可能でしょうか？",
        faq_dd8:"オンラインにて可能です。お気軽にお問い合わせください。",
        faq_dt9:"日本語があまりできないないのですが入学可能でしょうか？",
        faq_dd9:"日本語ベースでの授業を行っていますが英語対応可能です。<br>お気軽にお問い合わせください。",
        //sushi-owners page
        sushi_owners_title:"寿司店様のお問い合わせフォーム",
        sushi_owners_txt1:"当校HPへの掲載や卒業生のご紹介などの",
        sushi_owners_txt2:"お問い合わせはこちらに記入してください。",
        sushi_company_name:"会社名",
        sushi_owners_name:"お名前",
        sushi_owners_address:"住所",
        sushi_owners_phone:"電話番号",
        sushi_owners_email:"メールアドレス",
        sushi_owners_faq:"お問い合わせ内容",
        sushi_owners_option1:"選択してください",
        sushi_owners_option5:"例：東京寿司職人アカデミー",
        sushi_owners_option6:"例：東京都中央区銀座2丁目11-19国光ビル4階",
        sushi_phone_input:"例：03-6278-7586",
        sushi_email_input:"例：example@example.com",
        sushi_owners_option2:"掲載について",
        sushi_owners_option3:"採用について",
        sushi_owners_option4:"その他",
        notes:"備考",
        sushi_owners_terms_1:"利用規約",
        sushi_owners_terms_2:"を必ずお読み頂き、",
        sushi_owners_terms_3:"同意するにチェックをいれてください。",
        sushi_owners_above_terms:"上記に同意する",
        btn_submit:"送信",
        //company page
        company_tab1:"経営理念",
        company_tab2:"代表挨拶",
        company_name:"名称",
        company_name_txt:"東京寿司職人アカデミー",
        company_address:"所在地",
        company_address_txt:"〒104-0061<br>東京都中央区銀座２丁目１１−１９国光ビル4階",
        company_map:"Google mapはこちら",
        company_access:"アクセス",
        company_access_txt:"「銀座一丁目」駅徒歩1分<br>「銀座」駅徒歩5分",
        company_established:"設立",
        company_established_txt:"2023年8月",
        company_executives:"役員",
        company_executives_txt:"代表  木村 太郎",
        company_capital:"資本金",
        company_capital_txt:"5,000万円",
        company_affiliated:"関連会社",
        company_affiliated_txt:"株式会社DYM",
        company_philosophy_title:"寿司を通じて、あなたの人生を支えたい。",
        company_philosophy_content:"「東京寿司職人育成アカデミー」は寿司の技術だけを教えるアカデミーではなく、生徒ひとりひとりの人生と共に生きることを考えたアカデミーです。一流の寿司店と大手人材会社をルーツに持つ「東京寿司職人育成アカデミー」では、卒業後のキャリアも最後まで支援させていただきます。",
        company_message:"代表講師挨拶",
        company_message_content:"当校では短期間で高級店、海外等の特殊な環境等どんなシチュエーションでもお客様に喜こんで頂き、稼げる職人を育てていきます。<br>最近では既製の食品が増えガリやオボロ等作らなくなってきていますが自家製にこだわる高級店やそもそも既製品が手に入りにくい海外でも困らないようにしっかり学んで頂きます。<br>入校された皆様には是非、本物の寿司を国内外問わず広めて色々なお客様に喜んで頂きしっかり稼いで欲しいです。",
        company_message_content2:"<span class='sm'>代表取締役</span>木立 健太",
        //tems page
        tems_content:"東京寿司職人育成アカデミー（以下「本教室」といいます。）は、株式会社東京寿司（以下「当社」といいます。）が運営する、寿司職人の育成（以下「本目的」といいます。）のための授業（以下「本授業」といいます。）を行う教室です。本利用規約（以下「本規約」といいます。）には、本授業の受講者（第２条第４号で定める意味を有します。）と、当社との間の権利義務関係が定められています。本教室への入学及び本授業の受講（以下「受講等」といいます。）に際しては、本規約の全文をお読みいただいたうえで、本規約に同意いただく必要があります。",
        tems_article1:"第1条　（適用）",
        tems_article1_li1:"本規約は、受講等に関する受講者と当社との間の権利義務関係を定めることを目的とし、受講者と当社との間の本授業の受講に関わる一切の関係に適用されます。",
        tems_article1_li2:"当社が別途定める受講等に関するルールは、本規約の一部を構成するものとします。",
        tems_article1_li3:"本規約の内容と、前項のルール、その他の本規約外における受講等に関する説明等とが異なる場合は、本規約の規定が優先して適用されるものとします。",
        tems_article2:"第2条　（定義）",
        tems_article2_content:"本規約において使用する以下の用語は、それぞれ、以下に定める意味を有するものとします。",
        tems_article2_li1:"「受講契約」とは、本規約を契約条件として、本規約第３条第５項に従い受講者と当社との間で締結される、受講等に関する契約を意味します。",
        tems_article2_li2:"「知的財産権」とは、著作権、特許権、実用新案権、意匠権、商標権、ノウハウその他の知的財産権（それらの権利を取得し、又はそれらの権利につき登録等を出願する権利を含みます。）を意味します。",
        tems_article2_li3_1:"「当社ウェブサイト」とは、そのドメインが「",
        tems_article2_li3_2:"」である、当社が運営するウェブサイト（理由の如何を問わず、当社のウェブサイトのドメイン又は内容が変更された場合は、当該変更後のウェブサイトを含みます。）を意味します。",
        tems_article2_li4:"「受講者」とは、本規約に基づいて受講等を行う者として、当社が受講等の申込みを承諾した個人を意味します。",
        tems_article2_li5:"「反社会的勢力等」とは、暴力団、暴力団員、右翼団体、反社会的勢力、その他これに準ずる者を意味します。",
        tems_article3:"第3条　（受講契約の成立）",
        tems_article3_li1:"受講等を希望する者（以下「受講希望者」といいます。）は、本規約を遵守することに同意し、かつ当社の定める一定の情報（以下「登録事項」といいます。）を当社の定める方法で当社に提供することにより、当社に対し、受講等を申込むことができます。",
        tems_article3_li2:"受講希望者は、魚介類等、本授業で扱う食材にアレルギーが無いことを確認のうえ、前項の申込みを行うものとします。",
        tems_article3_li3:"本教室で扱う食材を口にしたことで、受講者に体調不良が生じた場合（アレルギー反応が出た場合を含みます。）であっても、当社に故意又は重過失がある場合を除き、当社は一切の責任を負わないものとします。",
        tems_article3_li4:"当社は、当社の基準に従って、第１項に基づく受講希望者による申込みの承諾の可否を判断し、当社が受講等を認める場合には、その旨、及び当社ウェブサイトへのログインID並びにパスワード(以下「パスワード等」といいます。)を当該受講希望者に通知します。",
        tems_article3_li5:"前項に定める通知の時点で、受講者と当社との間に本規約を内容とする受講契約が成立し、受講者は、本規約に従い受講等を行うことができるようになります。",
        tems_article3_li6:"当社は、受講希望者が、以下の各号のいずれかに該当する場合は、申込みを拒否することがあり、またその理由について一切開示義務を負いません。",
        tems_article3_li6_1:"健康面、安全面、衛生面等の観点から、受講者としてふさわしくないと当社が判断した場合",
        tems_article3_li6_2:"当社に提供した登録事項の全部又は一部につき虚偽、誤記又は記載漏れがあった場合",
        tems_article3_li6_3:"未成年者、成年被後見人、被保佐人又は被補助人のいずれかであり、法定代理人、後見人、保佐人又は補助人の同意等を得ていなかった場合",
        tems_article3_li6_4:"反社会的勢力等である、又は資金提供その他を通じて反社会的勢力等の維持、運営もしくは経営に協力もしくは関与する等反社会的勢力等との何らかの交流もしくは関与を行っていると当社が判断した場合",
        tems_article3_li6_5:"過去に当社との契約に違反した者又はその関係者であると当社が判断した場合",
        tems_article3_li6_6:"第１２条第１項に定める措置を受けたことがある場合",
        tems_article3_li6_7:"その他、当社が当該申込みを承諾することが適当でないと判断した場合",
        tems_article4:"第4条　（登録事項の変更）",
        tems_article4_content:"受講者は、登録事項に変更があった場合、当社の定める方法により、当該変更事項を遅滞なく当社に通知するものとします。",
        tems_article5:"第5条　（パスワード及びユーザーIDの管理）",
        tems_article5_li1:"受講者は、自己の責任において、パスワード等を適切に管理及び保管するものとし、これを第三者に利用させ、又は貸与、譲渡、名義変更、売買等をしてはならないものとします。",
        tems_article5_li2:"パスワード等の管理不十分、使用上の過誤、第三者の使用等によって生じた損害に関する責任は受講者が負うものとします。",
        tems_article6:"第6条　（料金及び支払方法）",
        tems_article6_li1:"受講者は、受講等にあたり、別途当社が定める入学金及び授業料（以下「授業料等」といいます。）を、当社が指定する支払期日までに、当社が指定する支払方法により、支払うものとします。",
        tems_article6_li2:"授業料等には、本授業にて寿司の実食をする際の費用、本授業で使用する食材並びに教材の費用、及び本授業で調理をする際に着用する白衣の費用が含まれます。",
        tems_article6_li3:"受講者が授業料等の支払を遅滞した場合、受講者は当社に対し、年14.6％の割合による遅延損害金を支払うものとします。",
        tems_article6_li4:"受講者は、授業料等の支払いを完了するまで、本授業を受講することはできません。",
        tems_article7:"第7条　（受講者の遵守事項）",
        tems_article7_content:"受講者は、以下の各号のいずれかに該当すると当社が判断する行為をしてはなりません。",
        tems_article7_li1:"法令に違反する行為又は犯罪行為に関連する行為",
        tems_article7_li2:"公序良俗に反する行為",
        tems_article7_li3:"当社の許可なく本授業の録音又は撮影を行う行為",
        tems_article7_li4:"本授業の際に香りの強い香水を着用する行為",
        tems_article7_li5:"本授業にて調理した寿司を持ち帰る行為",
        tems_article7_li6:"本教室の運営又は本授業の進行を妨害するおそれのある行為",
        tems_article7_li7:"第三者（他の受講者を含みます。以下同様です。）に成りすます行為",
        tems_article7_li8:"第三者をして、本授業を受講させる行為",
        tems_article7_li9:"当社又は第三者の知的財産権、肖像権、プライバシーの権利、名誉、その他の権利又は利益を侵害する行為",
        tems_article7_li10:"他の受講者の情報を収集する行為",
        tems_article7_li11:"宣伝、広告、勧誘、又は営業行為",
        tems_article7_li12:"当社又は第三者に対する詐欺又は脅迫行為",
        tems_article7_li13:"当社又は第三者に不利益、損害又は不快感を与える行為",
        tems_article7_li14:"反社会的勢力等へ利益を供与する行為",
        tems_article7_li15:"面識のない異性との出会いを目的とした行為",
        tems_article7_li16:"前各号の行為を直接又は間接に惹起し、又は容易にする行為",
        tems_article7_li17:"前各号の行為を試みる行為",
        tems_article7_li18:"その他、当社が不適切であると判断する行為",
        tems_article7_li19:"受講者は、本授業で調理を行う場合、前項に加え、以下の各号を遵守しなければなりません。",
        tems_article7_li19_1:"肩につく長い髪は結ぶこと",
        tems_article7_li19_2:"長い爪は切ること",
        tems_article7_li19_3:"指輪、ブレスレット、腕時計等の手指及び腕周りの装飾品を外すこと",
        tems_article7_li19_4:"手指に怪我がある場合、手袋を着用すること",
        tems_article7_li19_5:"その他、衛生・風評等の理由から当社が特に遵守を求めた事項",
        tems_article7_li20:"受講者は、本授業の受講に際し、貴重品を自らの責任で管理するものとし、受講者が貴重品を紛失し、又は盗難に遭った場合は、当社に故意又は重過失がある場合を除き、当社は一切の責任を負わないものとします。",
        tems_article7_li21:"受講者は、本授業の受講に際し生じた事故、怪我及び第三者との紛争（以下「紛争等」といいます。）につき、自ら責任を負うものとし、当該紛争等につき、当社に故意又は重過失がある場合を除き、当社は一切の責任を負わないものとします。",
        tems_article8:"第8条　（本授業の欠席）",
        tems_article8_content:"受講者が本授業を欠席する場合、当社に対し、当日の授業開始までに、欠席する旨の連絡をするものとします。",
        tems_article9:"第9条　（本授業の休講）",
        tems_article9_content:"当社は、以下の各号のいずれかに該当する場合には、本授業を休講することができるものとします。なお、当社は、休講する際は予め受講者に連絡いたします。",
        tems_article9_li1:"本授業の講師が本授業に参加できなくなった場合",
        tems_article9_li2:"本授業に利用する食材が入手できなかった場合",
        tems_article9_li3:"地震、落雷、火災、風水害、停電、天災地変などの不可抗力により本授業の実施ができなくなった場合",
        tems_article9_li4:"その他、当社が休講が必要と判断した場合",
        tems_article10:"第10条　(本授業の修了)",
        tems_article10_li1:"当社は、本授業の全課程の80％以上に出席し、かつ、当社が別途定める成績を修めた受講者について、本教室を修了したものと判断し、修了証を授与します。",
        tems_article10_li2:"本授業への遅刻又は早退は、欠席とみなします。",
        tems_article10_li3:"受講者が本教室を修了できなかった場合でも、当社の責に帰すべき事由による場合を除き、当社は、再度の本授業及び授業料等の返金はいたしません。",
        tems_article11:"第11条　（権利帰属）",
        tems_article11_li1:"本教室に関する知的財産権は全て当社又は当社に利用を許諾している者に帰属しており、本規約に基づく受講等は、本教室に関する知的財産権の利用許諾を意味するものではありません。",
        tems_article11_li2:"受講者は、当社から提供される本授業の動画及び教材等の一切を公開してはならず、また、第三者へ貸与又は譲渡してはなりません。",
        tems_article12:"第12条　（退学等）",
        tems_article12_li1:"当社は、受講者が、以下の各号のいずれかに該当する場合は、事前に通知又は催告することなく、当該受講者について、本授業の受講を一時的に禁止し、又は受講契約を解除し、本教室から退学させることができます。",
        tems_article12_li1_1:"本規約のいずれかの条項に違反した場合",
        tems_article12_li1_2:"登録事項に虚偽の事実があることが判明した場合",
        tems_article12_li1_3:"支払停止もしくは支払不能となり、又は破産手続開始、民事再生手続開始、会社更生手続開始、特別清算開始もしくはこれらに類する手続の開始の申立てがあった場合",
        tems_article12_li1_4:"当社からの問い合わせその他の回答を求める連絡に対して30日間以上応答がない場合",
        tems_article12_li1_5:"第３条第６項各号に該当する場合",
        tems_article12_li1_6:"その他、当社が受講者として相応しくないと合理的に判断した場合",
        tems_article12_li2:"前項各号のいずれかに該当した場合、受講者は、当社に対して負っている債務の一切について当然に期限の利益を失い、直ちに当社に対して全ての債務を履行するものとします。",
        tems_article12_li3:"受講者が第１項に従い退学となった場合、当社は、当社のキャンセルポリシーに従い、受講者から支払われた授業料等の返金をいたします。",
        tems_article13:"第13条　（受講契約の有効期間及び自主退学）",
        tems_article13_li1:"受講契約の有効期間は、受講契約の成立日から、当該受講契約にかかる本授業の課程を全て修了する日まで、又は受講契約の成立日から6ヶ月間（以下「受講期限」といいます。）のいずれか早い日までとします。受講期限までに本授業の課程を修了するよう、本授業の振替等をされる際はご注意ください。",
        tems_article13_li2:"受講者は、当社に債務不履行がある場合に限り、受講契約を中途で解除することができます。",
        tems_article13_li3:"受講者が前項に基づき受講契約を解除した場合、当社は、当社のキャンセルポリシーに従い、受講者から支払われた授業料等の返金をいたします。",
        tems_article14:"第14条　（本授業の内容の変更、終了）",
        tems_article14_li1:"当社は、当社の都合により、本授業の内容を変更し、又は本教室を閉校することができます。",
        tems_article14_li2:"前項の場合、当社は受講者に事前に通知するものとします。",
        tems_article15:"第15条　（本教室の運営の再委託等）[f51]",
        tems_article15_content:"当社は、本教室の運営の全部または一部を第三者に再委託することができるものとします。",
        tems_article16:"第16条　（保証の否認及び免責）",
        tems_article16_li1:"当社は、本教室が本目的以外の、受講者の特定の目的に適合すること、第三者の知的財産権、肖像権、プライバシーの権利、名誉、その他の権利又は利益を侵害しないこと、及び継続的に利用できることについて、明示又は黙示を問わず何ら保証するものではありません。",
        tems_article16_li2:"当社は、当社に故意又は重過失がある場合を除き、本教室に関して受講者が被った損害につき、受講者が当社に支払った授業料等の金額を超えて、賠償する責任を負わないものとします。",
        tems_article16_li3:"本教室に関連して受講者又は第三者との間において生じた紛争については、受講者が自己の責任によって解決するものとします。",
        tems_article17:"第17条　（秘密保持）",
        tems_article17_content:"受講者は、本教室に関連して当社が受講者に対して開示した情報について、当社の事前の書面による承諾がある場合を除き、秘密に取扱うものとし、本目的にのみ利用し、第三者に一切開示等しないものとします。",
        tems_article18:"第18条　（競業禁止）",
        tems_article18_content:"受講者は、受講契約の有効期間中及び受講契約終了後１年間は、その名義及び態様の如何を問わず、本教室と同種又は類似の営業を行ってはならないものとします。",
        tems_article19:"第19条　（受講者の個人情報の取扱い）",
        tems_article19_content:"当社は、受講者の個人情報を、別途当社の定めるプライバシーポリシーに従って取り扱うものとします。",
        tems_article20:"第20条　（本規約等の変更）",
        tems_article20_li1:"当社は、当社が必要と認めた場合に、本規約を変更できるものとします。",
        tems_article20_li2:"本規約を変更する場合、変更後の本規約の施行時期及び内容を当社ウェブサイト上での掲示その他の適切な方法により周知し、又は受講者に通知します。",
        tems_article20_li3:"法令上受講者の同意が必要となる本規約の変更を行う場合、当社は、当社所定の方法で受講者の同意を得るものとします。",
        tems_article21:"第21条　（連絡／通知）",
        tems_article21_li1:"本教室に関する問い合わせ、その他受講者から当社に対する連絡又は通知、及び本規約の変更に関する通知、その他当社から受講者に対する連絡又は通知は、当社の定める方法で行うものとします。",
        tems_article21_li2:"当社が登録事項に含まれるメールアドレスその他の連絡先に連絡又は通知を行った場合、受講者は当該連絡又は通知を受領したものとみなします。",
        tems_article22:"第22条　（受講契約上の地位の譲渡等）",
        tems_article22_li1:"受講者は、当社の書面による事前の承諾なく、受講契約上の地位又は本規約に基づく権利もしくは義務につき、第三者に対し、譲渡、移転、担保設定、その他の処分をすることはできません。",
        tems_article22_li2:"当社は本教室にかかる事業を他社に譲渡した場合には、当該事業譲渡に伴い受講契約上の地位、本規約に基づく権利及び義務並びに受講者の登録事項その他受講者の登録事項を当該事業譲渡の譲受人に譲渡することができるものとし、受講者は、かかる譲渡につき本項において予め同意したものとします。なお、本項に定める事業譲渡には、通常の事業譲渡のみならず、会社分割その他事業が移転するあらゆる場合を含むものとします。",
        tems_article23:"第23条　（分離可能性）",
        tems_article23_content:"本規約のいずれかの条項又はその一部が、法令等により無効又は執行不能と判断された場合であっても、本規約の残りの規定及び一部が無効又は執行不能と判断された規定の残りの部分は、継続して完全に効力を有するものとします。",
        tems_article24:"第24条　（準拠法及び裁判管轄）",
        tems_article24_li1:"本規約及び受講契約の準拠法は日本法とします。",
        tems_article24_li2:"本規約又は受講契約に起因し、又は関連する一切の紛争については、訴額に応じて、東京簡易裁判所又は東京地方裁判所を第一審の専属的合意管轄裁判所とします。",
        tems_article24_day:"【2025年1月7日制定】",
        //contact page
        contact:"お問い合わせ",
        contact_content:"フォームに必要事項とお問い合わせ内容をご入力の上、「送信」ボタンをクリックしてください。",
        contact_tab1:"資料請求",
        contact_tab2:"入学願書申込",
        contact_form:"以下のフォームに入力してください。",
        contact_form_name:"お名前",
        contact_form_name_input:"お名前を入力してください",
        contact_form_postal:"郵便番号",
        contact_form_postal_input:"例：1234567",
        contact_form_refecture:"都道府県",
        contact_refecture_option1:"都道府県を選択",
        contact_refecture_option2:"北海道",
        contact_refecture_option3:"青森県",
        contact_refecture_option4:"岩手県",
        contact_refecture_option5:"宮城県",
        contact_refecture_option6:"秋田県",
        contact_refecture_option7:"山形県",
        contact_refecture_option8:"福島県",
        contact_refecture_option9:"茨城県",
        contact_refecture_option10:"栃木県",
        contact_refecture_option11:"群馬県",
        contact_refecture_option12:"埼玉県",
        contact_refecture_option13:"千葉県",
        contact_refecture_option14:"東京都",
        contact_refecture_option15:"神奈川県",
        contact_refecture_option16:"新潟県",
        contact_refecture_option17:"富山県",
        contact_refecture_option18:"石川県",
        contact_refecture_option19:"福井県",
        contact_refecture_option20:"山梨県",
        contact_refecture_option21:"長野県",
        contact_refecture_option22:"岐阜県",
        contact_refecture_option23:"静岡県",
        contact_refecture_option24:"愛知県",
        contact_refecture_option25:"三重県",
        contact_refecture_option26:"滋賀県",
        contact_refecture_option27:"京都府",
        contact_refecture_option28:"大阪府",
        contact_refecture_option29:"兵庫県",
        contact_refecture_option30:"奈良県",
        contact_refecture_option31:"和歌山県",
        contact_refecture_option32:"鳥取県",
        contact_refecture_option33:"島根県",
        contact_refecture_option34:"岡山県",
        contact_refecture_option35:"広島県",
        contact_refecture_option36:"山口県",
        contact_refecture_option37:"徳島県",
        contact_refecture_option38:"香川県",
        contact_refecture_option39:"愛媛県",
        contact_refecture_option40:"高知県",
        contact_refecture_option41:"福岡県",
        contact_refecture_option42:"佐賀県",
        contact_refecture_option43:"長崎県",
        contact_refecture_option44:"熊本県",
        contact_refecture_option45:"大分県",
        contact_refecture_option46:"宮崎県",
        contact_refecture_option47:"鹿児島県",
        contact_refecture_option48:"沖縄県",
        contact_email:"メール",
        contact_email_input:"メールアドレスを入力してください",
        contact_phone:"電話番号",
        contact_phone_input:"電話番号を入力してください",
        contact_form_tab2:"受講者情報",
        contact_form_student:"受講者名",
        contact_course_applied:"申込コース",
        course_gender:"性別",
        course_male:"男",
        course_female:"女",
        course_birth_day:"生年月日",
        course_birth_day_input:"生年月日を入力してください",
        course_dominant:"利き腕",
        course_left:"右",
        course_right:"左",
        course_food:"食物アレルギー",
        yes:"ある",
        no:"ない",
        course_allergens:"アレルギー反応が起きる食材",
        contact_cooking:"料理人/シェフ経験",
        contact_emergency:"緊急連絡先",
        contact_emergency_address:"上記の方のお住まい（緊急連絡先）",
        contact_address_same:"ご本人様と同じ",
        contact_address_different:"ご本人様と異なる",
        contact_size:"制服サイズ",
        contact_size_option:"サイズを選択してください",
        contact_shoe:"靴サイズ",
        contact_shoe_option2:"23.0センチ",
        contact_shoe_option3:"23.4センチ",
        contact_shoe_option4:"24.0センチ",
        contact_shoe_option5:"24.5センチ",
        contact_shoe_option6:"25.0センチ",
        contact_shoe_option7:"25.5センチ",
        contact_shoe_option8:"26.0センチ",
        contact_shoe_option9:"26.5センチ",
        contact_shoe_option10:"27.0センチ",
        contact_shoe_option11:"27.5センチ",
        contact_purchase:"物品の購入",
        contact_purchase_content:"柳葉包丁、出刃包丁、和牛刀、砥石、包丁収納袋、盛り箸、コックシューズ<br>※既にお持ちの方は単品購入も可能です。お問い合わせ備考欄にてご相談ください。",
        contact_purchase_option1:"購入しない",
        contact_purchase_option2:"購入する（右利き用）8万円（税込）",
        contact_purchase_option3:"購入する（左利き用）10万円（税込）",
        contact_payment_method:"お支払い方法",
        contact_payment_method_option1:"現金振込",
        contact_payment_method_option2:"クレジットカード",
        contact_payment_method_option3:"教育ローン",
        //intensive page
        intensive_person:"こんな方が受講",
        intensive_person_txt:"様々な方が一緒に受講しています！<br>それぞれにあった教え方をしております。",
        intensive_person_li1:"全く料理をしたことがないが、寿司職人にキャリアチェンジしたい。",
        intensive_person_li2:"飲食店で働いているが、寿司職人になって世界で働きたい。",
        intensive_person_li3:"寿司職人になって稼げるようになりたい。",
        intensive_skills:"短期で3年目程度の技術を習得",
        intensive_skills_content:"東京寿司職人育成アカデミーでは多くの技術獲得が可能です。<br>未経験で寿司店に就職した場合、雑用や皿洗いなどが最初メインになってしまい、魚を捌くまでに時間がかかってしまう場合や、握るのがそもそも数年経ってからなどの可能性があります。<br>東京寿司職人育成アカデミーではすべての時間を魚を捌く、寿司を握る時間に使えるので、未経験で就職するよりも遥かに早いスピードで技術を習得することが可能です。",
        intensive_techniques:"寿司の調理技術を習得",
        intensive_techniques_content:"代表講師の木立は様々な店舗での経験があり、多くの経験と技術を生徒一人ひとりに伝授いたします。<br>寿司店の中でも様々な業態がございますが、どこにいっても通用する本物の技術を習得することが可能です。",
        intensive_curriculum:"カリキュラム",
        intensive_curriculum_content:"カリキュラムの一例をご紹介します。",
        intensive_curriculum_th1:"1週目",
        intensive_curriculum_th2:"2週目",
        intensive_curriculum_th3:"3週目",
        intensive_curriculum_th4:"4週目",
        intensive_curriculum_th5:"5週目",
        intensive_curriculum_th6:"6週目",
        intensive_curriculum_th7:"7週目",
        intensive_curriculum_th8:"8週目",
        intensive_curriculum_td_course:"授業内容",
        intensive_curriculum_td1:"寿司職人といしての心構えと衛生に関して",
        intensive_curriculum_td2:"光物の仕込み、切り付け",
        intensive_curriculum_td3:"光物の仕込み、切り付け",
        intensive_curriculum_td4:"かんぴょうの仕込み",
        intensive_curriculum_td5:"英語での料理説明",
        intensive_curriculum_td6:"光物の仕込み、切り付け（テスト）",
        intensive_curriculum_td7:"穴子の仕込み<br class='pc_break'>（テスト）",
        intensive_curriculum_td8:"旬の食材の仕込み",
        intensive_curriculum_td9:"道具の扱い方、手入れの仕方",
        intensive_curriculum_td10:"〆ものの仕込み切り付け",
        intensive_curriculum_td11:"〆ものの仕込み切り付け",
        intensive_curriculum_td12:"オボロの仕込み",
        intensive_curriculum_td13:"豊洲市場見学",
        intensive_curriculum_td14:"白身魚の仕込み、切り付け（テスト）",
        intensive_curriculum_td15:"細巻き（テスト）",
        intensive_curriculum_td16:"お任せの献立作成及び原価計算<br class='pc_break'>（テスト）",
        intensive_curriculum_td17:"シャリ酢に関して",
        intensive_curriculum_td18:"白身魚の仕込み、切り付け",
        intensive_curriculum_td19:"白身魚の仕込み、切り付け",
        intensive_curriculum_td20:"どんこの仕込み",
        intensive_curriculum_td21:"光物の仕込み、切り付け（応用）",
        intensive_curriculum_td22:"冷凍鮪の扱い、切り付け（テスト）",
        intensive_curriculum_td23:"太巻き（テスト）",
        intensive_curriculum_td24:"お任せの献立試作（テスト）",
        intensive_curriculum_td25:"米のとぎ方、炊き方",
        intensive_curriculum_td26:"冷凍鮪と生鮪の扱いと切り付け",
        intensive_curriculum_td27:"穴子の仕込み、炊き方",
        intensive_curriculum_td28:"魚卵の仕込み<br class='pc_break'>（いくら、数の子等）",
        intensive_curriculum_td29:"〆ものの仕込み切り付け（応用）",
        intensive_curriculum_td30:"貝類の仕込み、切り付け（テスト）",
        intensive_curriculum_td31:"１人前の握り<br class='pc_break'>（テスト）",
        intensive_curriculum_td32:"テスト結果を踏まえ",
        intensive_curriculum_td33:"シャリきり",
        intensive_curriculum_td34:"薬味、妻物、野菜の仕込み（桂向き等）",
        intensive_curriculum_td35:"原価計算について",
        intensive_curriculum_td36:"太巻きの巻き方",
        intensive_curriculum_td37:"甲殻類の仕込み<br class='pc_break'>（応用）",
        intensive_curriculum_td38:"卵焼きの焼き方、切り付け（テスト）",
        intensive_curriculum_td39:"原価計算<br class='pc_break'>（テスト）",
        intensive_curriculum_td40:"毎日仕込んだ食材の握り及び軍艦、巻きの練習",
        intensive_curriculum_td41:"基本的な光物の仕込み、切り付け",
        intensive_curriculum_td42:"基本的な貝類の仕込み、切り付け",
        intensive_curriculum_td43:"甲殻類の仕込み（エビカニ、イカタコ等）",
        intensive_curriculum_td44:"裏巻きの巻き方（カルフォルニアロール等）",
        intensive_curriculum_td45:"貝類の仕込み、切り付け（応用）",
        intensive_curriculum_td46:"おまかせの組み立て方について",
        intensive_curriculum_td47:"旬の食材の仕込み",
        intensive_curriculum_td48:"及び毎日の反復練習",
        intensive_curriculum_td49:"基本的な白身魚の仕込み、切り付け",
        intensive_curriculum_td50:"基本的な卵焼きの焼き方、切り付け",
        intensive_curriculum_td51:"貝類の仕込み、切り付け（煮蛤等）",
        intensive_curriculum_td52:"毎日仕込んだ食材の握り及び軍艦、巻きの練習",
        intensive_curriculum_td53:"冷凍鮪と生鮪の扱いと切り付け（応用）",
        intensive_curriculum_td54:"前菜、焼き物、煮物、蒸し物、刺身等について",
        intensive_curriculum_td55:"テスト結果を踏まえ",
        intensive_curriculum_td56:"寿司佑にて招待客にお任せの提供",
        intensive_curriculum_td57:"基本的な冷凍鮪の扱い、切り付け",
        intensive_curriculum_td58:"基本的な細巻きの巻き方",
        intensive_curriculum_td59:"調味料について（煮切り、煮ツメ、貝ツメ等）",
        intensive_curriculum_td60:"及び毎日の反復練習",
        intensive_curriculum_td61:"白身魚の仕込み、切り付け（応用）",
        intensive_curriculum_td62:"旬の食材の仕込み",
        intensive_curriculum_td63:"毎日仕込んだ食材の握り及び軍艦、巻きの練習",
        intensive_curriculum_td64:"だしの取り方",
        intensive_curriculum_td65:"毎日仕込んだ食材の握り及び軍艦、巻きの練習",
        intensive_curriculum_td66:"毎日仕込んだ食材の握り及び軍艦、巻きの練習",
        intensive_curriculum_td67:"ガリの仕込み",
        intensive_curriculum_td68:"１人前の握りの組み立て方について",
        intensive_curriculum_td69:"毎日仕込んだ食材の握り及び軍艦、巻きの練習",
        intensive_curriculum_td70:"及び毎日の反復練習",
        intensive_curriculum_td71:"基本的な薬味、妻物、野菜の仕込み",
        intensive_curriculum_td72:"及び毎日の反復練習",
        intensive_curriculum_td73:"及び毎日の反復練習",
        intensive_curriculum_td74:"卵焼きの焼き方、切り付け（カステラ等）",
        intensive_curriculum_td75:"毎日仕込んだ食材の握り及び軍艦、巻きの練習",
        intensive_curriculum_td76:"及び毎日の反復練習",
        intensive_curriculum_td77:"毎日仕込んだ食材の握り及び軍艦、巻きの練習",
        intensive_curriculum_td78:"笹切り",
        intensive_curriculum_td79:"及び毎日の反復練習",
        intensive_curriculum_td80:"及び毎日の反復練習",
        intensive_curriculum_td81:"寿司佑にてランチ",
        intensive_tuition:"受講費用",
        intensive_tuition_content:"24回払いで月々33,712 円！",
        intensive_tuition_th1:"入学金　(税込)",
        intensive_tuition_td1:"22万円",
        intensive_tuition_th2:"授業料　(税込)",
        intensive_tuition_td2:"55万円",
        intensive_flow:"入学までの流れ",
        intensive_flow_content:"ご入学まで担当が手厚くサポートします。",
        intensive_flow_txt:"コース案内・学費に戻る",
    },
    en: {
        languageJa:"Japanese",
        languageEn:"English",
        // header
        school: "School",
        course: "Course",
        placement:"Career Support",
        instructor:"Instructor",
        faq:"FAQ",
        sushiOwners:"Sushi Owners",
        //footer
        address:"Address:4th Floor, Kokkō Building, 2-11-19 Ginza, Chuo-ku, Tokyo 104-0061",
        tel:"TEL: 03-6278-7586<br>Business Days: Monday, Tuesday, Thursday, Friday, Saturday (excluding national holidays)",
        access:"＜Access＞<br>2-minute walk from Ginza-itchome Station<br>4-minute walk from Higashi-Ginza Station<br>6-minute walk from Ginza Station<br>8-minute walk from Yurakucho Station",
        intensive:"Intensive Training Course",
        company:"Company Profile",
        tems:"Terms of Use",
        //FV
        mvisualTopH1:"Tokyo Sushi Glow Up Academy",
        mvisualTopH2:"Become a sushi chef who can thrive on the global stage",
        mvisualSub:"〈Limited to the June–August 2025 course〉<br>Total fee of ¥770,000 now only ¥300,000！Only 5 spots left！ ",
        //CTA
        btn_cta01:"Click to request materials <br>or join a free school tour",
        btn_cta02:"For inquiries, click here",
        btn_cta03:"Apply for Admission",
        cta_text:"We also welcome inquiries by phone.",
        //東京寿司職人<br>育成アカデミーとは
        academy_jp:"What is the<br> Tokyo Sushi Glow Up Academy?",
        academy_sec:"Train under true sushi masters and aim to<br> become a sushi chef in as little as two months",
        academy_text:"We are an academy that trains high-level sushi chefs from scratch in just two months—chefs who are ready to work immediately at restaurants both in Japan and abroad.<br>Even the basics—such as cooking rice, filleting fish and shaping sushi—can vary greatly depending on the type of restaurant. <br>At our academy, you’ll learn not only the skills required at high-end restaurants, casual establishments and conveyor belt sushi shops, but also how to adapt when working overseas, where equipment, water, fish and seasonings may differ.<br>After graduation, we provide job support for positions at high-end restaurants, casual sushi spots, conveyor belt sushi shops and opportunities abroad.",
        //course
        course_btn:"See more course information",
        cta_sec_btn01:"Request information (free)",
        //instructors
        instructors_jp:"Top-Class Industry Sushi Chefs as instructors",
        instructors_text:"From how to use a knife to how to make sushi, we teach everything carefully from the basics.<br>With a small class size, we provide detailed and attentive instruction, so even beginners can feel confident attending.",
        instructors_btn:"See more about our instructors",
        //enroll
        enroll_jp:"For those interested in enrollment",
        tuition:"Tuition fees",
        maintenance:"A day of a Student",
        enroll_maintenance:"Watch lessons<br> in videos",
        //strengths
        strengths_jp:"Strengths of the Tokyo Sushi Glow Up Academy",
        strengths_list1:"Partnership with <br>the High-End Sushi Restaurant<br>「Ginza Sushi Yu」",
        strengths_list2:"As part of the DYM Company Ltd,<br class='sp_break'> which has a wide range of sectors such as healthcare, IT,  human resources and <br>numerous post-graduation job placements to offer.",
        strengths_list3:"We can also introduce graduates to five-star hotels and Michelin-starred restaurants.",
        //faq
        faq_1:"Is there support after graduation?",
        faq_2:"Our school is operated by a parent organization involved of businesses, human resources, web services, real estate, both domestically and internationally. We provide job placement and startup support according to your preferences, both in Japan and abroad.",
        faq_3:"Are there any entrance requirements?",
        faq_4:"There are no specific requirements. Focus on learning well, after graduation, you'll be ready to earn a good income.",
        faq_5:"Is it okay if I have no cooking experience?",
        faq_6:"At our academy, we start from the basics. You'll learn how to hold a knife, maintain tools and more. Even experienced chefs will benefit from our curriculum, as it includes lessons on making handmade products that are typically pre-made, allowing you to acquire new skills.",
        faq_7:"Can I become a sushi chef in two months?",
        faq_8:"Yes, you will learn not only the technical skills but also the mindset of a sushi chef, proper etiquette at the counter, how to explain dishes in English, and other essential skills that will prepare you for real-world work at a professional level.",
        faq_btn:"See more",
        //access page
        home:"Home",
        reasons_jp:"Reasons to choose <br class='sp_break'>the Tokyo Sushi Glow Up Academy",
        point1_title:"Intensive short-term curriculum",
        point1_txt:"Our program is a focused, two-month intensive course.<br>With hands-on training in sushi making and knife skills in every session, you'll develop muscle memory and reach a professional level by the time you graduate.",
        point2_title:"Become Job-Ready for a wide range of workplaces!",
        point2_txt:"You'll learn various ways to handle fish-whether prioritizing quality, speed, aging, or freezing-depending on the needs of the workplace.We also offer lessons on making items like gari (pickled ginger) and oboro (sweetened fish flakes), which are typically pre-made in most restaurants.",
        point3_title:"Job placement & Startup support",
        point3_txt:"Our parent company, DYM Co. Ltd. (with a link to the website), operates a wide range of businesses both in Japan and abroad, including human resources, web services and real estate. Thanks to this strong network, we provide extensive support for employment and starting your own business after graduation.",
        comparison_jp:"Comparison with other schools",
        comparison_text:"Aim to become a globally successful sushi chef under the guidance of real masters.",
        comparison_th1:"Tokyo Sushi Glow Up Academy",
        comparison_th2:"Culinary School",
        comparison_th3:"Ticket-Based Sushi Class",
        comparison_th4:"Sushi Chef Training School",
        comparison_td1:"Study Duration",
        comparison_td2:"2 months",
        comparison_td3:"24 months",
        comparison_td4:"1 to 6 days",
        comparison_td5:"2 months",
        comparison_td6:"Class Hours",
        comparison_td7:"Approx. 200 hours",
        comparison_td8:"Approx. 3,500 hours <br>(mainly classroom learning)",
        comparison_td9:"1 to 200 hours",
        comparison_td10:"Approx. 200 hours",
        comparison_td11:"Curriculum",
        comparison_td12:"Acquire practical skills and knowledge tailored to real kitchen settings",
        comparison_td13:"Mainly focused on Japanese cuisine rather than sushi",
        comparison_td14:"Choose only the classes you want (some require purchasing many class tickets)",
        comparison_td15:"Short-term, nigiri-focused classes",
        comparison_td16:"Class Size",
        comparison_td17:"12 students",
        comparison_td18:"Approx. 40 students",
        comparison_td19:"12 students",
        comparison_td20:"24 students",
        comparison_td21:"Tuition Fees",
        comparison_td22_p1:"<span class='lrg'>¥700,000</span> (excl. tax) ",
        comparison_td22_p2:"¥770,000 <span class='sm'>(incl. 10% tax)</span>",
        comparison_td23:"Enrollment fee: ¥250,000<br>Tuition: ¥3,540,000",
        comparison_td24:"From ¥7,000 per session<br>200 sessions: ¥700,000",
        comparison_td25:"Enrollment fee: ¥165,000<br>Tuition: ¥715,000",
        comparison_td26:"Ingredients",
        comparison_td27:"Procurement of a wide variety of unprocessed ingredients, just like in high-end restaurants",
        comparison_td28:"Bulk-purchased basic seafood",
        comparison_td29:"Seafood selected to match class content",
        comparison_td30:"Includes block-cut, unprocessed ingredients",
        comparison_td31:"Post-Graduation Support",
        comparison_td32:"Job placement in Japan and abroad, career consultation after employment, and support for opening your own business",
        comparison_td33:"Mainly job postings",
        comparison_td34:"Mainly internal recruitment",
        comparison_td35:"Specialized job listing websites",
        access_jp:"Access",
        access_address:"Tokyo Sushi Glow Up Academy – Ginza Campus",
        access_post:"〒104-0061<br>4th Floor, Kokkō Building, 2-11-19 Ginza, Chuo-ku, Tokyo",
        access_transportation:"Transportation Access",
        access_station:"1-minute walk from Ginza-itchome Station<br>5-minute walk from Ginza Station",
        map_view:"View on Google Maps",
        //course and fees page
        course_fees_title:"Course Information & Tuition Fees",
        course_features:"Course Features",
        course_tuition:"Tuition",
        course_tuition_loan:"Tuition Loan",
        course_information:"This course is designed to help even complete beginners build strong skills and knowledge.",
        course_centent:"Course Content",
        course_centent_txt:"Short-term intensive course, 5 times a week",
        course_enrollment:"Enrollment Fee",
        course_enrollment_txt:"¥220,000 (tax included)",
        course_fees:"Tuition Fee",
        course_fees_txt:" ¥550,000 (tax included)",
        course_payment:"Installment Payment",
        course_payment_txt:"¥33,712/month for 24 months",
        course_day:"Class Days",
        course_day_txt:"every Monday, Tuesday, Wednesday, Thursday, and Friday",
        course_hours:"Class Hours",
        course_hours_txt:"9:00 AM – 4:00 PM",
        details:"More details here",
        course_features_title:"Providing the highest quality classes at one of the lowest prices in the industry",
        course_features_txt:"In order to reduce the financial burden of enrollment as much as possible, Tokyo Sushi Glow Up Academy has lowered tuition fees to the minimum, compared to the typical tuition range of ¥880,000 to ¥1,100,000. Educational loans are also available, allowing students to pay in 24 monthly installments of ¥33,712 (including interest), making it affordable even with part-time job income during the enrollment period.We provide practical training at top-tier sushi restaurants in Ginza and lessons from master instructors, offering a level of quality that other academies cannot match.",
        course_loans_txt1:"Loan approval is easily available through the company we recommend.",
        course_loans_txt2:"2-Month Intensive Training Course ",
        course_loans_fees:"Total Cost: ¥770,000 (tax included)",
        course_loans_th1:"Installment",
        course_loans_th2:"Monthly Payment (tax included)",
        course_loans_td1:"24 payments",
        course_loans_td2:"¥37,712 per month",
        course_loans_td3:"36 payments",
        course_loans_td4:"¥23,008 per month",
        course_loans_td5:"60 payments",
        course_loans_td6:"¥14,460 per month",
        course_loans_btn_title:"Request for Information - Accepted Anytime!",
        //就職サポート page
        placement_support:"DYM Company Ltd<br class='sp'> Provides Full Support!",
        placement_support_title:"The DYM Company Ltd is a large company with over 2,000 employees and annual sales exceeding 30 billion yen. <br>In the field of recruitment, DYM Company Ltdhas received high recognition, including ranking first in customer satisfaction on Oricon. <br>Therefore, for post-graduation employment support, we guarantee the highest standards with the 'Tokyo Sushi Glow Up Academy.'",
        //instructor page
        instructor_jp:"Experienced Instructors",
        instructor_represent:"Head Instructor",
        instructor_represent_name:"Kenta Kodate",
        instructor_represent_txt1:"With over 30 years of hands-on experience at renowned restaurants, luxury establishments, and famous hotels both in Japan and abroad, Kenta Kodate now serves as an instructor.",
        instructor_represent_txt2:"Career Highlights (Partial List)",
        instructor_th1:"Japan",
        instructor_td1:"Sushiya Ichikan (A famous high-end restaurant in Daikanyama, popular with celebrities)",
        instructor_td2:"atelierMORIMOTO・XEX (A renowned luxury restaurant in Roppongi, produced by Iron Chef Morimoto)",
        instructor_td3:"Tankuma Kitaten, Royal Park Hotel Shiodome (Sushi head chef at this prestigious Kyoto-style restaurant, established in 1928)",
        instructor_td4:"Grand Hyatt Tokyo, Rokuriku (Sushi restaurant at one of Tokyo’s top luxury hotels)",
        instructor_td5:"ANA, Haneda and Narita Airport Airline Lounges",
        instructor_td6:"Sushi Shiogama Port Ginza, Gokoku (A famous high-end restaurant in Ginza)",
        instructor_th2:"United States",
        instructor_td7:"Sushizen (A prestigious, long-established sushi restaurant in Manhattan, New York)",
        instructor_th3:"Germany",
        instructor_td8:"The Westin Grand Frankfurt, Sushi Moto (A long-established high-end sushi restaurant in Germany)",
        //faq page
        faq_dt1:"Is there support after graduation?",
        faq_dd1:"Our institution is part of a larger organization that operates a wide range of businesses domestically and internationally, including human resources, web services, and real estate. We provide job placement and business start-up support both domestically and abroad, tailored to your preferences.",
        faq_dt2:"Are there any entry requirements?",
        faq_dd2:"There are no specific entry requirements. We encourage you to study diligently and earn well after graduation.",
        faq_dt3:"Is it okay if I have no prior cooking experience?",
        faq_dd3:"At our school, you will learn from the basics. We will teach you the proper way to hold a knife and how to maintain your tools. Additionally, even for those with experience, we offer a curriculum that enables you to make items that are usually reliant on pre-made products, allowing you to acquire new skills.",
        faq_dt4:"Can I become a sushi chef in two months?",
        faq_dd4:"We will teach you not only the technical skills but also the mindset of a sushi chef, including proper behavior at the counter and how to explain dishes in English. You will learn to a level that is suitable for real-world applications.",
        faq_dt5:"I live in a rural area. Do you have dormitories or other facilities?",
        faq_dd5:"We do not have dormitories or similar facilities, but since our organization also operates in real estate and other businesses, please feel free to consult with us.",
        faq_dt6:"Is it possible to pay the tuition fees in installments?",
        faq_dd6:"We offer loan options, so please feel free to contact us for more information.",
        faq_dt7:"Is there an age limit?",
        faq_dd7:"There is no age limit. As long as you have motivation and energy, you're good to go!",
        faq_dt8:"I live overseas. Is it possible to have an interview or tour?",
        faq_dd8:"Yes, we can arrange online interviews or tours. Please feel free to contact us.",
        faq_dt9:"I am not very proficient in Japanese. Can I still enroll?",
        faq_dd9:"Classes are conducted in Japanese, but we can provide support in English as well. Please feel free to contact us.",
        //sushi-owners page
        sushi_owners_title:"Contact Form for Sushi Restaurants",
        sushi_owners_txt1:"Please fill out this form for inquiries regarding listings",
        sushi_owners_txt2:"on our website or introductions of graduates.",
        sushi_company_name:"Company Name",
        sushi_owners_name:"Name",
        sushi_owners_address:"Address",
        sushi_owners_phone:"Phone Number",
        sushi_owners_email:"Email Address",
        sushi_owners_faq:"Inquiry Details",
        sushi_owners_option1:"Please select an option",
        sushi_owners_option5:"Example：Tokyo Sushi Glow Up Academy",
        sushi_owners_option6:"Example：4th Floor, Kokkō Building, 2-11-19 Ginza, Chuo-ku, Tokyo",
        sushi_phone_input:"Example：03-6278-7586",
        sushi_email_input:"Example：example@example.com",
        sushi_owners_option2:"Listing Request",
        sushi_owners_option3:"Recruitment Inquiry",
        sushi_owners_option4:"Other",
        notes:"Notes",
        sushi_owners_terms_1:"The Terms of Use",
        sushi_owners_terms_2:" Please read it carefully and",
        sushi_owners_terms_3:"check the box to agree.",
        sushi_owners_above_terms:"I agree to the above terms.",
        btn_submit:"Submit",
        //company page
        company_tab1:"Corporate Philosophy",
        company_tab2:"Representative's Greeting",
        company_name:"Name",
        company_name_txt:"Tokyo Sushi Glow Up Academy",
        company_address:"Location",
        company_address_txt:"〒104-0061<br>4th Floor, Kokko Building, 2-11-19 Ginza, Chuo-ku, Tokyo",
        company_map:"[Google Map Here]",
        company_access:"Access",
        company_access_txt:"1-minute walk from 'Ginza-itchome' Station<br> 5-minute walk from 'Ginza' Station",
        company_established:"Established",
        company_established_txt:"August 2023",
        company_executives:"Executives",
        company_executives_txt:"Representative Director, Taro Kimura",
        company_capital:"Capital",
        company_capital_txt:"50 million yen",
        company_affiliated:"Affiliated Company",
        company_affiliated_txt:"DYM Company Ltd",
        company_philosophy_title:"Supporting Your Life Through Sushi.",
        company_philosophy_content:"The 'Tokyo Sushi Glow Up Academy' is not just an academy that teaches sushi skills, but one that considers living alongside each student's life journey. With roots in top-tier sushi restaurants and major recruitment companies, the 'Tokyo Sushi Glow Up Academy' provides continuous support for your career even after graduation.",
        company_message:"Message from the Head Instructor",
        company_message_content:"At our academy, we aim to train skilled sushi chefs who can delight customers and earn a living, no matter the setting—whether it’s a high-end restaurant, overseas, or any other unique environment. Recently, ready-made products like gari (pickled ginger) and oboro (shredded fish) have become more common, and many places no longer make them from scratch. However, at high-end restaurants that insist on homemade ingredients, or overseas where ready-made products are hard to find, we make sure to provide thorough training so you won't face any difficulties.For everyone who joins our academy, I hope you will spread the art of authentic sushi, both domestically and internationally, and delight customers while earning a solid income.",
        company_message_content2:"<span class='sm'>CEO</span>Taro Kimura",
        //tems page
        tems_content:"Tokyo Sushi Glow Up Academy (hereinafter referred to as 'the Academy') is operated by Tokyo Sushi Co., Ltd. (hereinafter referred to as 'the Company') and offers courses for the training of sushi chefs (hereinafter referred to as 'the Purpose'). These Terms and Conditions (hereinafter referred to as 'the Agreement') outline the rights and obligations between the participants of the course (as defined in Article 2, Section 4) and the Company. When enrolling in the Academy and taking the course (hereinafter referred to as 'Participation'), it is necessary to read the entire Agreement and agree to its terms.",
        tems_article1:"Article 1 (Applicability)",
        tems_article1_li1:"The purpose of this Agreement is to define the rights and obligations between the participant and the Company regarding Participation. This Agreement applies to all relations between the participant and the Company related to the course.",
        tems_article1_li2:"Any additional rules set by the Company regarding Participation will form part of this Agreement.",
        tems_article1_li3:"In case of any discrepancies between the contents of this Agreement, the rules mentioned in the previous section, and any other explanations regarding Participation outside of this Agreement, the provisions of this Agreement will take precedence.",
        tems_article2:"Article 2 (Definitions)",
        tems_article2_content:"The following terms used in this Agreement shall have the meanings defined below:",
        tems_article2_li1:"'Enrollment Agreement' refers to the contract concerning Participation, which is concluded between the participant and the Company based on the terms of this Agreement, in accordance with Article 3, Section 5.",
        tems_article2_li2:"'Intellectual Property Rights' refers to copyrights, patent rights, utility model rights, design rights, trademark rights, know-how, and other intellectual property rights (including the right to acquire or apply for registration of such rights).",
        tems_article2_li3_1:"'Company Website' refers to the website operated by the Company, with the domain",
        tems_article2_li3_2:", and includes any modifications or changes made to the domain or content of the website, regardless of the reason.",
        tems_article2_li4:"'Participant' refers to the individual who, based on this Agreement, has applied for Participation and whose application has been accepted by the Company.",
        tems_article2_li5:"'Antisocial Forces' refers to organizations such as organized crime groups, gang members, right-wing groups, antisocial organizations, or any other similar entities.",
        tems_article3:"Article 3 (Formation of Enrollment Agreement)",
        tems_article3_li1:"Individuals wishing to participate (hereinafter referred to as 'Prospective Participants') may apply for Participation by agreeing to comply with this Agreement and providing the required information (hereinafter referred to as 'Registration Information') to the Company in the prescribed manner.",
        tems_article3_li2:"Prospective Participants must confirm that they do not have allergies to seafood or other ingredients used in the course before submitting the application as mentioned in the previous section.",
        tems_article3_li3:"The Company shall not be held responsible for any health issues (including allergic reactions) that arise from consuming ingredients used in the course, unless the Company is found to be intentionally negligent or grossly negligent.",
        tems_article3_li4:"The Company will evaluate whether to accept the application based on its own criteria. If the application is accepted, the Company will notify the Prospective Participant of the acceptance, as well as the login ID and password for the Company website (hereinafter referred to as 'Login Credentials').",
        tems_article3_li5:"Upon the notification mentioned in the previous section, the Enrollment Agreement, based on this Agreement, shall be formed between the participant and the Company, and the participant will be able to participate in the course in accordance with this Agreement.",
        tems_article3_li6:"The Company may refuse the application if any of the following conditions apply, and it is not obligated to disclose the reasons for the refusal: ",
        tems_article3_li6_1:"If the Company determines that the applicant is not suitable to be a participant based on health, safety, or hygiene concerns. ",
        tems_article3_li6_2:"If the Registration Information provided is false, contains errors, or is incomplete. ",
        tems_article3_li6_3:"If the applicant is a minor, an adult under guardianship, or a person under curatorship or assistance, and has not obtained the consent of their legal representative, guardian, curator, or assistant. ",
        tems_article3_li6_4:"If the applicant is associated with antisocial forces, or if the Company determines that the applicant is involved in any way with antisocial forces, including through financial support or cooperation. ",
        tems_article3_li6_5:"If the Company determines that the applicant has previously violated a contract with the Company or is related to such a person. ",
        tems_article3_li6_6:"If the applicant has previously been subject to measures as described in Article 12, Section 1. ",
        tems_article3_li6_7:"If the Company determines that accepting the application is inappropriate for any other reason.",
        tems_article4:"Article 4 (Change of Registration Information)",
        tems_article4_content:"The participant shall promptly notify the Company of any changes to the Registration Information in the prescribed manner.",
        tems_article5:"Article 5 (Management of Passwords and User ID)",
        tems_article5_li1:"The participant shall be responsible for properly managing and safeguarding their login credentials, including passwords, and shall not allow third parties to use, lend, transfer, change the name on, or sell them.",
        tems_article5_li2:"The participant shall bear full responsibility for any damage caused by improper management, misuse, or third-party use of the login credentials.",
        tems_article6:"Article 6 (Fees and Payment Methods)",
        tems_article6_li1:"The participant shall pay the enrollment fee and tuition fees (hereinafter referred to as 'Tuition Fees') by the due date specified by the Company, using the payment method designated by the Company.",
        tems_article6_li2:"The Tuition Fees include the costs for sushi tasting during the course, ingredients and materials used in the course, and the cost of the white coat worn during cooking classes.",
        tems_article6_li3:"If the participant fails to pay the Tuition Fees on time, they shall pay the Company a late penalty of 14.6% annually on the overdue amount.",
        tems_article6_li4:"The participant may not attend the course until the Tuition Fees have been fully paid.",
        tems_article7:"Article 7 (Obligations of Participants)",
        tems_article7_content:"The participant must not engage in any of the following actions, as determined by the Company: ",
        tems_article7_li1:"Acts that violate laws or are related to criminal activities. ",
        tems_article7_li2:"Acts that are against public order or morals. ",
        tems_article7_li3:"Recording or photographing the course without permission. ",
        tems_article7_li4:"Wearing strongly scented perfume during the course. ",
        tems_article7_li5:"Taking home sushi made during the course. ",
        tems_article7_li6:"Acts that may disturb the operation or progress of the course. ",
        tems_article7_li7:"Impersonating another person (including other participants). ",
        tems_article7_li8:"Allowing a third party to attend the course in their place. ",
        tems_article7_li9:"Infringing upon the intellectual property rights, portrait rights, privacy rights, honor, or other rights or interests of the Company or a third party. ",
        tems_article7_li10:"Collecting information about other participants. ",
        tems_article7_li11:"Engaging in advertising, solicitation, or business activities. ",
        tems_article7_li12:"Committing fraud or threats against the Company or a third party. ",
        tems_article7_li13:"Causing harm, damage, or discomfort to the Company or a third party. ",
        tems_article7_li14:"Providing benefits to antisocial forces. ",
        tems_article7_li15:"Engaging in activities for the purpose of meeting strangers of the opposite sex.",
        tems_article7_li16:"Engaging in or facilitating any of the above actions, directly or indirectly. ",
        tems_article7_li17:"Attempting to engage in any of the above actions. ",
        tems_article7_li18:"Any other actions the Company deems inappropriate.",
        tems_article7_li19:"In addition to the above, when participating in cooking during the course, the participant must also comply with the following: ",
        tems_article7_li19_1:"Tie up long hair that reaches the shoulders.",
        tems_article7_li19_2:"Cut long nails.",
        tems_article7_li19_3:"Remove rings, bracelets, watches, and other decorations on hands and arms. ",
        tems_article7_li19_4:"Wear gloves if they have any injuries on their hands. ",
        tems_article7_li19_5:"Comply with any other hygiene or reputation-related requirements specified by the Company.",
        tems_article7_li20:"The participant is responsible for managing their valuables during the course. In case of loss or theft of valuables, the Company is not responsible unless it is due to intentional or gross negligence on the part of the Company.",
        tems_article7_li21:"The participant assumes responsibility for any accidents, injuries, or disputes with third parties (hereinafter referred to as 'Disputes'). The Company will not be liable for such Disputes, except in cases of intentional or gross negligence by the Company.",
        tems_article8:"Article 8 (Absence from the Course)",
        tems_article8_content:"If the participant is absent from the course, they must notify the Company by the start of the class on that day.",
        tems_article9:"Article 9 (Cancellation of the Course)",
        tems_article9_content:"The Company may cancel the course under any of the following circumstances. In such cases, the Company will notify the participant in advance: ",
        tems_article9_li1:"If the instructor is unable to attend the course. ",
        tems_article9_li2:"If the ingredients required for the course are unavailable. ",
        tems_article9_li3:"If natural disasters such as earthquakes, lightning, fires, floods, power outages, or other force majeure events prevent the course from being conducted. ",
        tems_article9_li4:"If the Company determines that the course should be canceled for any other reason.",
        tems_article10:"Article 10 (Completion of the Course)",
        tems_article10_li1:"The Company will consider the participant to have completed the course if they attend at least 80% of the total classes and achieve the results defined separately by the Company. A completion certificate will be awarded to those who meet these requirements.",
        tems_article10_li2:"Tardiness or leaving early during the course will be considered as an absence.",
        tems_article10_li3:" If the participant is unable to complete the course, the Company will not provide a retake or refund of the Tuition Fees, unless the failure is due to reasons attributable to the Company.",
        tems_article11:"Article 11 (Ownership of Rights)",
        tems_article11_li1:"All intellectual property rights related to this academy belong to the company or those who have granted the company permission to use them, and participation in the classes as per these terms and conditions does not imply any license to use the intellectual property rights related to the academy.",
        tems_article11_li2:"The participant shall not publicly disclose any videos, materials, or other content provided in this class by the company, nor lend, transfer, assign, or otherwise distribute them to third parties.",
        tems_article12:"Article 12 (Withdrawal and Termination)",
        tems_article12_li1:"The company may, without prior notice or warning, temporarily prohibit a participant from attending the class or cancel the participation contract and expel the participant from the academy if the participant falls under any of the following circumstances:",
        tems_article12_li1_1:"Violation of any provision of these terms and conditions.",
        tems_article12_li1_2:"Discovery of false information in the registration details.",
        tems_article12_li1_3:"Suspension or inability to pay, or the initiation of bankruptcy, civil rehabilitation, corporate reorganization, special liquidation, or similar procedures.",
        tems_article12_li1_4:"No response to inquiries or requests from the company for 30 days or more.",
        tems_article12_li1_5:"The participant falls under any of the situations listed in Article 3, Section 6.",
        tems_article12_li1_6:" Other cases where the company reasonably determines the participant is unsuitable.",
        tems_article12_li2:"If the participant falls under any of the above circumstances, the participant will lose all benefits of the due date and must immediately fulfill all obligations to the company.",
        tems_article12_li3:"If the participant is expelled based on the above section, the company will refund the tuition fees paid by the participant in accordance with the company's cancellation policy.",
        tems_article13:"Article 13 (Duration of the Participation Contract and Voluntary Withdrawal)",
        tems_article13_li1:"The validity period of the participation contract shall be from the date of conclusion until the participant has completed all courses under the contract or 6 months from the date of conclusion (the 'participation period'), whichever is earlier. The participant should be mindful of this duration when making class reschedules.",
        tems_article13_li2:"The participant may terminate the contract only if the company fails to fulfill its obligations.",
        tems_article13_li3:"If the participant terminates the contract in accordance with the previous section, the company will refund the tuition fees paid by the participant in accordance with the company's cancellation policy.",
        tems_article14:"Article 14 (Changes to the Class Content and Closure)",
        tems_article14_li1:"The company may change the class content or close the academy for reasons related to the company.",
        tems_article14_li2:"In such cases, the company will notify the participant in advance.",
        tems_article15:"Article 15 (Outsourcing of Academy Operations)",
        tems_article15_content:"The company may outsource all or part of the academy operations to a third party.",
        tems_article16:"Article 16 (Disclaimer of Warranties and Liability)",
        tems_article16_li1:"The company does not guarantee, whether express or implied, that the academy will meet the participant's specific goals, not infringe upon third-party intellectual property rights, or be available for continuous use.",
        tems_article16_li2:"The company shall not be liable for any damages incurred by the participant beyond the amount of the tuition fees paid to the company, unless caused by intentional misconduct or gross negligence on the part of the company.",
        tems_article16_li3:"Any disputes arising between the participant and third parties related to the academy shall be resolved by the participant at their own responsibility.", 
        tems_article17:"Article 17 (Confidentiality)",
        tems_article17_content:"The participant shall treat all information disclosed by the company in relation to the academy as confidential, and shall not disclose it to third parties without the prior written consent of the company, except for the purpose of the classes.",
        tems_article18:"Article 18 (Non-Compete)",
        tems_article18_content:"The participant shall not engage in the same or similar business as the academy, whether in name or form, during the validity period of the participation contract and for one year after the termination of the contract.",
        tems_article19:"Article 19 (Handling of Participant's Personal Information)",
        tems_article19_content:"The company will handle the participant's personal information in accordance with the privacy policy separately established by the company.",
        tems_article20:"Article 20 (Changes to these Terms)",
        tems_article20_li1:"The company may change these terms if deemed necessary.",
        tems_article20_li2:"In the event of changes, the company will inform the participant of the revised terms and their effective date via posting on the company website or other appropriate methods.",
        tems_article20_li3:" If a change to these terms requires the participant's consent under the law, the company will obtain the participant's consent through the method specified by the company.",
        tems_article21:"Article 21 (Communication / Notifications)",
        tems_article21_li1:"Any inquiries, communications, or notifications from the participant to the company, or notifications related to changes in these terms, shall be made in accordance with the method prescribed by the company.",
        tems_article21_li2:"If the company sends a notification to the participant’s registered email address or other contact details, the participant is deemed to have received such notification.",
        tems_article22:"Article 22 (Transfer of Contract Rights)",
        tems_article22_li1:" The participant may not transfer, assign, or otherwise dispose of their rights or obligations under the participation contract without the prior written consent of the company.",
        tems_article22_li2:"If the company transfers the business related to the academy to another company, the company may transfer the rights and obligations under the participation contract, as well as the participant’s registration details, to the transferee. The participant agrees to such transfer in advance under this section.",
        tems_article23:"Article 23 (Severability)",
        tems_article23_content:"If any provision or part of these terms is judged to be invalid or unenforceable due to laws or regulations, the remaining provisions will remain fully valid and enforceable.",
        tems_article24:"Article 24 (Governing Law and Jurisdiction)",
        tems_article24_li1:"These terms and the participation contract shall be governed by Japanese law.",
        tems_article24_li2:"Any disputes arising from or related to these terms or the participation contract shall be subject to the exclusive jurisdiction of the Tokyo Summary Court or the Tokyo District Court, depending on the amount in dispute.",
        tems_article24_day:"[Established on January 7, 2025]",
        //contact page
        contact:"Contact Us",
        contact_content:"Please fill in the required fields and your inquiry in the form, then click the 'Submit' button.",
        contact_tab1:"Request materials",
        contact_tab2:"Apply for Admission",
        contact_form:"Please fill out the form below.",
        contact_form_name:"Name",
        contact_form_name_input:"Please enter your name",
        contact_form_postal:"Postal Code",
        contact_form_postal_input:"Example: 1234567",
        contact_form_refecture:"Prefecture",
        contact_refecture_option1:"Please select your prefecture",
        contact_refecture_option2:"Hokkaido",
        contact_refecture_option3:"Aomori",
        contact_refecture_option4:"Iwate",
        contact_refecture_option5:"Miyagi",
        contact_refecture_option6:"Akita",
        contact_refecture_option7:"Yamagata",
        contact_refecture_option8:"Fukushima",
        contact_refecture_option9:"Ibaraki",
        contact_refecture_option10:"Tochigi",
        contact_refecture_option11:"Gunma",
        contact_refecture_option12:"Saitama",
        contact_refecture_option13:"Chiba",
        contact_refecture_option14:"Tokyo",
        contact_refecture_option15:"Kanagawa",
        contact_refecture_option16:"Niigata",
        contact_refecture_option17:"Toyama",
        contact_refecture_option18:"Ishikawa",
        contact_refecture_option19:"Fukui",
        contact_refecture_option20:"Yamanashi",
        contact_refecture_option21:"Nagano",
        contact_refecture_option22:"Gifu",
        contact_refecture_option23:"Shizuoka",
        contact_refecture_option24:"Aichi",
        contact_refecture_option25:"Mie",
        contact_refecture_option26:"Shiga",
        contact_refecture_option27:"Kyoto",
        contact_refecture_option28:"Osaka",
        contact_refecture_option29:"Hyogo",
        contact_refecture_option30:"Nara",
        contact_refecture_option31:"Wakayama",
        contact_refecture_option32:"Tottori",
        contact_refecture_option33:"Shimane",
        contact_refecture_option34:"Okayama",
        contact_refecture_option35:"Hiroshima",
        contact_refecture_option36:"Yamaguchi",
        contact_refecture_option37:"Tokushima",
        contact_refecture_option38:"Kagawa",
        contact_refecture_option39:"Ehime",
        contact_refecture_option40:"Kochi",
        contact_refecture_option41:"Fukuoka",
        contact_refecture_option42:"Saga",
        contact_refecture_option43:"Nagasaki",
        contact_refecture_option44:"Kumamoto",
        contact_refecture_option45:"Oita",
        contact_refecture_option46:"Miyazaki",
        contact_refecture_option47:"Kagoshima",
        contact_refecture_option48:"Okinawa",
        contact_email:"Email",
        contact_email_input:"Please enter your email address",
        contact_phone:"Phone Number",
        contact_phone_input:"Please enter your phone number",
        contact_form_tab2:"Student Information",
        contact_form_student:"Student Name",
        contact_course_applied:"Course Applied For",
        course_gender:"Gender",
        course_male:"Male",
        course_female:"Female",
        course_birth_day:"Date of Birth",
        course_birth_day_input:"Please enter your date of birth",
        course_dominant:"Dominant Hand",
        course_left:"Left",
        course_right:"Right",
        course_food:"Food Allergies",
        yes:"Yes",
        no:"No",
        course_allergens:"Please specify the allergens",
        contact_cooking:"Cooking Experience",
        contact_emergency:"Emergency Contact",
        contact_emergency_address:"Emergency Contact Address",
        contact_address_same:"Same as the above address",
        contact_address_different:"Different from the above address",
        contact_size:"Uniform Size",
        contact_size_option:"Please select a size",
        contact_shoe:"Shoe Size",
        contact_shoe_option2:"23.0 cm",
        contact_shoe_option3:"23.5 cm",
        contact_shoe_option4:"24.0 cm",
        contact_shoe_option5:"24.5 cm",
        contact_shoe_option6:"25.0 cm",
        contact_shoe_option7:"25.5 cm",
        contact_shoe_option8:"26.0 cm",
        contact_shoe_option9:"26.5 cm",
        contact_shoe_option10:"27.0 cm",
        contact_shoe_option11:"27.5 cm",
        contact_purchase:"Purchase of Equipment",
        contact_purchase_content:"Yanagiba Knife, Deba Knife, Japanese Chef Knife, Sharpening Stone, Knife Storage Bag, Serving Chopsticks, Chef Shoes<br>※ If you already own any of these items, you can purchase them individually. Please consult the remarks section for details.",
        contact_purchase_option1:"Do Not Purchase",
        contact_purchase_option2:"Purchase (For Right-Handed) 80,000 yen (including tax)",
        contact_purchase_option3:"Purchase (For Left-Handed) 100,000 yen (including tax)",
        contact_payment_method:"Payment Method",
        contact_payment_method_option1:"Bank Transfer",
        contact_payment_method_option2:"Credit Card",
        contact_payment_method_option3:"Education Loan",
        //intensive page
        intensive_person:"Who Can Take the Course",
        intensive_person_txt:"A variety of people are taking the course together! We provide teaching methods that are tailored to each individual.",
        intensive_person_li1:"Someone who has never cooked before but wants to switch careers and become a sushi chef.",
        intensive_person_li2:"Someone currently working in the food service industry but wants to become a sushi chef and work internationally.",
        intensive_person_li3:"Someone who wants to become a sushi chef and earn a good income.",
        intensive_skills:"Mastering Skills in a Short Period – Around 3 Years of Experience",
        intensive_skills_content:"At the Tokyo Sushi Chef Training Academy, you can acquire a wide range of skills.<br>If you join a sushi restaurant without prior experience, your main tasks will likely involve menial work such as washing dishes or handling basic tasks, and it may take a long time before you're allowed to handle fish or start making sushi. In some cases, it could take years before you even get the chance to begin making sushi.<br>At the Tokyo Sushi Chef Training Academy, all of your time is dedicated to working with fish and making sushi. This allows you to master these skills much faster than you would if you were to start at a sushi restaurant without experience.",
        intensive_techniques:"Master Sushi Cooking Techniques",
        intensive_techniques_content:"Our head instructor, Kodate, has experience working at various establishments and will pass on his extensive knowledge and skills to each student. While there are different types of sushi restaurants, our program enables you to acquire genuine, versatile techniques that will be applicable wherever you go.",
        intensive_curriculum:"Curriculum",
        intensive_curriculum_content:"Example Curriculum",
        intensive_curriculum_th1:"Week 1",
        intensive_curriculum_th2:"Week 2",
        intensive_curriculum_th3:"Week 3",
        intensive_curriculum_th4:"Week 4",
        intensive_curriculum_th5:"Week 5",
        intensive_curriculum_th6:"Week 6",
        intensive_curriculum_th7:"Week 7",
        intensive_curriculum_th8:"Week 8",
        intensive_curriculum_td_course:"Course Content",
        intensive_curriculum_td1:"Mindset and hygiene as a sushi chef",
        intensive_curriculum_td2:"Preparation and cutting of light fish",
        intensive_curriculum_td3:"Preparation and cutting of light fish",
        intensive_curriculum_td4:"Preparation of kanpyou (dried gourd strips)",
        intensive_curriculum_td5:"Explaining dishes in English",
        intensive_curriculum_td6:"Test: Preparation and cutting of light fish",
        intensive_curriculum_td7:"Preparation of anago<br class='pc_break'>(Test)",
        intensive_curriculum_td8:"Preparation of seasonal ingredients",
        intensive_curriculum_td9:"Handling and maintenance of tools",
        intensive_curriculum_td10:"Preparation and cutting of marinated fish (Shime-mono)",
        intensive_curriculum_td11:"Preparation and cutting of marinated fish (Shime-mono)",
        intensive_curriculum_td12:"Preparation of Oboro (seasoned mashed fish)",
        intensive_curriculum_td13:"Tour of Toyosu Market",
        intensive_curriculum_td14:"Preparation and cutting of white fish (Practical test)",
        intensive_curriculum_td15:"Hosomaki (Thin roll sushi) – Practical test",
        intensive_curriculum_td16:"Creation of Omakase menus and cost calculation<br class='pc_break'> (Practical test)",
        intensive_curriculum_td17:"About Shari-zu (sushi vinegar)",
        intensive_curriculum_td18:"Preparation and cutting of white fish",
        intensive_curriculum_td19:"Preparation and cutting of white fish",
        intensive_curriculum_td20:"Preparation of Donko (a type of fish)",
        intensive_curriculum_td21:"Preparation and cutting of Hikarimono (silver-skinned fish)",
        intensive_curriculum_td22:"Handling and cutting of frozen tuna (Practical test)",
        intensive_curriculum_td23:"Futomaki (Thick roll sushi) – Practical test",
        intensive_curriculum_td24:"Omakase menu trial creation (Practical test)",
        intensive_curriculum_td25:"How to wash and cook rice",
        intensive_curriculum_td26:"Handling and cutting of both frozen and fresh tuna",
        intensive_curriculum_td27:"Preparation and simmering of Anago (sea eel)",
        intensive_curriculum_td28:"Preparation of fish roe<br class='pc_break'> (e.g., Ikura, Kazunoko)",
        intensive_curriculum_td29:"Preparation and cutting of marinated fish (Shime-mono)",
        intensive_curriculum_td30:"Preparation and cutting of shellfish (Practical test)",
        intensive_curriculum_td31:"One serving of Nigiri sushi <br class='pc_break'>(Practical test)",
        intensive_curriculum_td32:"Review and evaluation based on test results",
        intensive_curriculum_td33:"Sharigiri (shaping vinegared rice for sushi)",
        intensive_curriculum_td34:"Preparation of garnishes, decorative elements, and vegetables (e.g., Katsuramuki technique)",
        intensive_curriculum_td35:"About cost calculation",
        intensive_curriculum_td36:"How to roll Futomaki (thick roll sushi)",
        intensive_curriculum_td37:"Preparation of crustaceans<br class='pc_break'>(Advanced)",
        intensive_curriculum_td38:"Cooking and cutting of Tamagoyaki (Japanese omelet) (Practical test)",
        intensive_curriculum_td39:"Cost calculation<br class='pc_break'> (Practical test)",
        intensive_curriculum_td40:"Practice making Nigiri, Gunkan, and rolls using daily-prepared ingredients",
        intensive_curriculum_td41:"Basic preparation and cutting of Hikarimono (silver-skinned fish)",
        intensive_curriculum_td42:"Basic preparation and cutting of shellfish",
        intensive_curriculum_td43:"Preparation of crustaceans (shrimp, crab, squid, octopus, etc.)",
        intensive_curriculum_td44:"How to roll Uramaki (inside-out rolls, e.g., California roll)",
        intensive_curriculum_td45:"Advanced preparation and cutting of shellfish",
        intensive_curriculum_td46:"How to structure an Omakase course",
        intensive_curriculum_td47:"Preparation of seasonal ingredients",
        intensive_curriculum_td48:"Daily repetition and practice",
        intensive_curriculum_td49:"Basic preparation and cutting of white fish",
        intensive_curriculum_td50:"Basic preparation and cutting of Tamagoyaki (Japanese omelet)",
        intensive_curriculum_td51:"Preparation and cutting of simmered shellfish (e.g., Nihamaguri)",
        intensive_curriculum_td52:"Practice making Nigiri, Gunkan, and rolls using daily-prepared ingredients",
        intensive_curriculum_td53:"Advanced handling and cutting of frozen and fresh tuna",
        intensive_curriculum_td54:"About appetizers, grilled dishes, simmered dishes, steamed dishes, sashimi, etc.",
        intensive_curriculum_td55:"Review and evaluation based on test results",
        intensive_curriculum_td56:"Serve Omakase to invited guests at Sushi Yuu",
        intensive_curriculum_td57:"Basic handling and cutting of frozen tuna",
        intensive_curriculum_td58:"Basic technique for rolling Hosomaki (thin rolls)",
        intensive_curriculum_td59:"About seasonings (e.g., Nikiri, Nitsume, Kaitsume)",
        intensive_curriculum_td60:"Daily repetition and practice",
        intensive_curriculum_td61:"Advanced preparation and cutting of white fish",
        intensive_curriculum_td62:"Preparation of seasonal ingredients",
        intensive_curriculum_td63:"Practice making Nigiri, Gunkan, and rolls using daily-prepared ingredients",
        intensive_curriculum_td64:"How to make Dashi (Japanese soup stock)",
        intensive_curriculum_td65:"Practice making Nigiri, Gunkan, and rolls using daily-prepared ingredients",
        intensive_curriculum_td66:"Practice making Nigiri, Gunkan, and rolls using daily-prepared ingredients",
        intensive_curriculum_td67:"Preparation of Gari (pickled ginger)",
        intensive_curriculum_td68:"How to assemble a one-serving Nigiri set",
        intensive_curriculum_td69:"Practice making Nigiri, Gunkan, and rolls using daily-prepared ingredients",
        intensive_curriculum_td70:"Daily repetition and practice",
        intensive_curriculum_td71:"Basic preparation of condiments, garnishes, and vegetables",
        intensive_curriculum_td72:"Daily repetition and practice",
        intensive_curriculum_td73:"Daily repetition and practice",
        intensive_curriculum_td74:"Cooking and cutting of Tamagoyaki (Japanese omelet – e.g., Castella-style)",
        intensive_curriculum_td75:"Practice making Nigiri, Gunkan, and rolls using daily-prepared ingredients",
        intensive_curriculum_td76:"Daily repetition and practice",
        intensive_curriculum_td77:"Practice making Nigiri, Gunkan, and rolls using daily-prepared ingredients",
        intensive_curriculum_td78:"Sasagiri (decorative bamboo leaf cutting)",
        intensive_curriculum_td79:"Daily repetition and practice",
        intensive_curriculum_td80:"Daily repetition and practice",
        intensive_curriculum_td81:"Lunch service at Sushi Yuu",
        intensive_tuition:"Tuition Fees",
        intensive_tuition_content:"¥33,712 per month with a 24-month payment plan!",
        intensive_tuition_th1:"Enrollment Fee (incl. tax)",
        intensive_tuition_td1:"¥220,000",
        intensive_tuition_th2:"Tuition Fee (incl. tax)",
        intensive_tuition_td2:"¥550,000",
        intensive_flow:"Admission Process",
        intensive_flow_content:"Our team will provide comprehensive support until your enrollment.",
        intensive_flow_txt:"Back to Courses & Tuition",
    }
};

const urlList = [
    { url: '/access', page: 'access.html', class: 'page page_access page-access'},
    { url: '/courses-and-fees', page: 'courses-and-fees.html' , class: 'page page_courses-and-fees page-courses-and-fees'},
    { url: '/career', page: 'career.html', class: 'page page_career page-career' },
    { url: '/instructors', page: 'instructors.html', class: 'page page_instructors page-instructors' },
    { url: '/faq', page: 'faq.html', class: 'page page_faq page-faq' },
    { url: '/sushi-owners', page: 'sushi-owners.html', class: 'page page_sushi-owners page-sushi-owners' },
    { url: '/company', page: 'company.html', class: 'page page_company page-company' },
    { url: '/contact', page: 'contact.html', class: 'page page_contact page-contact' },
    { url: '/', page: 'index.html', class: ''},
    { url: '/courses-and-fees/intensive', page: 'courses-and-fees/intensive.html', class: 'page page_intensive page-intensive' },
    { url: '/maintenance', page: 'maintenance.html', class: '' },
    { url: '/terms', page: 'terms.html', class: 'page page_terms page-terms'},
];
  
const pageConfigs = {
    'index.html': {
      scripts: ['js/top.js'],
      init: 'initTopPage'
    },
    'access.html': {
      scripts: ['js/table.js'],
      init: 'initTable'
    },
    'intensive.html': {
      scripts: ['js/table.js'],
      init: 'initTable'
    },
    'faq.html': {
      scripts: ['js/faq.js'],
      init: 'initFaq'
    },
    'contact.html': {
        scripts: ['js/contact.js'],
        init: 'initContact'
    }
};

$(document).ready(function() {
    // Mở/đóng dropdown
    $('.custom-select .selected-option').on('click', function (e) {
        e.stopPropagation();
        $('.select-options').toggle();
    });

    // Click ra ngoài thì đóng dropdown
    $(document).on('click', function () {
        $('.select-options').hide();
    });

    // Mặc định ngôn ngữ là tiếng nhật
    let lang = 'ja';

    // Hàm thay đổi ngôn ngữ
    function changeLanguage() {
        // Lặp qua các phần tử có thuộc tính 'key'
        $('[key]').each(function() {
            let key = $(this).attr('key');
            const value = arrLang[lang][key];

            // Nếu có thẻ HTML trong text thì dùng html(), ngược lại dùng text()
            if (value.includes('<br>') 
                || value.includes('</') 
                || value.includes("<br class='sp_break'>") 
                || value.includes("<span class='sm'>")
                ||value.includes("<br class='pc_break'>")
                ||value.includes("<br class='sp'>") ) {
                $(this).html(value);
            } else {
                $(this).text(value);
            }
        });
        const submitInput = arrLang[lang]["btn_submit"];
        $('.wpcf7-submit').val(submitInput);

        $('[data-i18n-key]').each(function () {
            const key = $(this).data('i18n-key');
            const text = arrLang[lang][key] || '';
            $(this).attr('placeholder', text);
          });
    }

   
    
    // Click chọn ngôn ngữ
    $('.select-options li').on('click', function () {
        lang = $(this).data('lang');
        const imgSrc = $(this).find('img').attr('src');
        let text = $(this).text();
        if (text == " Japanese") {
            text = "日本語";
        }
        if (text == " 英語") {
            text = "English";
            localStorage.setItem("showLanguageEn", "true");
        }
        
        // Cập nhật selected option
        $('.selected-option').html(`<img src="${imgSrc}" alt=""> ${text}`);

        // Đóng dropdown
        $('.select-options').hide();

        // Gọi hàm xử lý đổi ngôn ngữ 
        changeLanguage();
    });

    const currentPath = window.location.pathname;
    const basePath = currentPath.replace(/\/[^\/]*$/, ''); // ví dụ /tssa

    function bindLanguageEvents() {
        $('a').on('click', function (e) {
            if (lang == 'en') {
                localStorage.setItem("showLanguageEn", "true");
            }
    
            const href = $(this).attr('href'); // ví dụ: contact.html/#tab03
            const urlParts = href.split('#');
    
            // 🛠 Xóa dấu '/' nếu có ở cuối
            let pathOnly = urlParts[0].replace(/\/$/, '');
            const hash = urlParts[1] ? `#${urlParts[1]}` : '';
    
            const matched = urlList.find(item =>
                pathOnly === item.url || pathOnly.endsWith(item.page)
            );
    
            if (matched) {
                e.preventDefault();
                const newUrl = basePath + matched.url + hash;
                history.pushState(null, null, newUrl);
                loadPage(matched, hash);
            }
        });
    }

    function loadScripts(scripts) {
        const promises = scripts.map(src => {
            // Nếu script đã tồn tại thì không load lại
            if ($(`script[src="${src}"]`).length > 0) {
                return Promise.resolve();
            }
    
            return new Promise((resolve, reject) => {
                const script = document.createElement('script');
                script.src = src;
                script.type = 'text/javascript';
                script.onload = resolve;
                script.onerror = reject;
                document.head.appendChild(script);
            });
        });
    
        return Promise.all(promises);
    }

    function loadPage(item, hash = '') {
        const baseUrl = window.location.origin + window.location.pathname.replace(/[^\/]*$/, '');
        const fullUrl = baseUrl + item.page;
        $.ajax({
            url: fullUrl,
            success: function (response) {
                const html = $('<div>').append($.parseHTML(response));
                const content = html.find('#wrapper').html();
                $('body').removeClass();
                $('body').addClass(item.class);

                if ($('script[src="js/common.js"]').length != 0) {
                    $('script[src="js/common.js"]').remove();
                }
 
                if(item.page == 'index.html'){
                    console.log('loadPage index');
                    // css
                    $("link[href='css/content.css']").remove();
                    $("<link>", {rel: "stylesheet",href: "css/top.css"}).appendTo("head");
                    //js
                    $('<script>', {src: 'js/top.js',type: 'text/javascript'}).appendTo('head');
                }else{
                    //css
                    $("link[href='css/top.css']").remove();
                    $('script[src="js/top.js"]').remove();

                    if ($('link[rel="stylesheet"][href="css/content.css"]').length != 0) {
                        $("link[href='css/content.css']").remove();
                        $("<link>", {rel: "stylesheet",href: "css/content.css"}).appendTo("head");
                    }else{
                        $("<link>", {rel: "stylesheet",href: "css/content.css"}).appendTo("head");
                    }
                }
    
                console.log("content",content)
                $('#wrapper').html(content);
                changeLanguage();
                bindLanguageEvents();
                console.log("hash",hash)
                // Cuộn đến phần tử có id tương ứng nếu có hash
                if (hash) {
                    const target = $(hash);
                    if (target.length) {
                        $('html, body').animate({
                            scrollTop: target.offset().top
                        }, 500);
                    }
                }

                const config = pageConfigs[item.page];
                if (!config) return;

                loadScripts(config.scripts).then(() => {
                    const initFn = window[config.init];
                    if (typeof initFn === 'function') {
                        initFn(); // ✅ Gọi đúng hàm khởi tạo, mỗi trang 1 lần
                    }
                });
    
                if (hash) {
                    setTimeout(() => {
                        const tabLink = $(`.tab_contact a[href="${hash}"]`);
                        if (tabLink.length) {
                            tabLink.trigger('click');
                        }
    
                        const target = $(hash);
                        if (target.length) {
                            $('html, body').animate({
                                scrollTop: target.offset().top
                            }, 300);
                        }
                    }, 100);
                }
            },
            error: function () {
                $('#wrapper').html('<p style="color:red;">❌ Lỗi tải trang!</p>');
            }
        });
    }
    
      

    if (localStorage.getItem("showLanguageEn") === "true") {
        // Cập nhật selected option
        $('.selected-option').html(`<img src="img/language/en.png" alt=""> English`);
        lang = 'en';
        // Xóa trạng thái để không ảnh hưởng lần tải sau
        localStorage.removeItem("showLanguageEn");
    }
    // Cập nhật văn bản khi trang được tải
    changeLanguage();
    bindLanguageEvents();
});


